Added players data classes and repository. Also refactored the code a…
it-kyrylo/project-a pull request #4
Opened 2021-08-27 19:45 UTC by MiroslavDionisiev

…ccording to the remarks, but made rebasing mistake in the previous branch.

2021-08-28 04:26 UTC, VelyanGedzhev approved these changes

2021-08-30 08:04 UTC, GeorgiKolev55 approved these changes

2021-08-30 08:33 UTC, it-kyrylo requested changes

2021-08-30 08:33 UTC, it-kyrylo commented on ProjectA/ProjectA/Auxiliary/KeyBuilder.cs
> +﻿namespace ProjectA.Auxiliary
let's put this class into Infrastructure or Builders or Helpers folders (honestly Auxiliary is kind of new to me naming)

2021-08-30 08:33 UTC, it-kyrylo commented on ProjectA/ProjectA/Clients/IFantasyPremierLeagueClient.cs
> +        Task<string> LoadBootstrapStaticPlayersDataTeamsAsync();
use complex types like similar to `Task<TeamsData>`

2021-08-30 08:33 UTC, it-kyrylo commented on ProjectA/ProjectA/Repositories/PlayersRepository.cs
> +public class PlayersRepository<T> : IPlayersRepository<T> where T : class
I would suggest using same approach as in the `TeamRepository`

2021-08-30 08:44 UTC, GeorgiKolev55 commented on ProjectA/ProjectA/Repositories/PlayersRepository.cs
> +public class PlayersRepository<T> : IPlayersRepository<T> where T : class
Kyrylo ,I guess you mean ,instead of this generic repo to create two separate repos and inject them both in the service if needed?

2021-08-30 09:14 UTC, MiroslavDionisiev commented on ProjectA/ProjectA/Clients/IFantasyPremierLeagueClient.cs
> +        Task<string> LoadBootstrapStaticPlayersDataTeamsAsync();
I used string because as the repository is Generic so that to avoid violating the DRY principle. Otherwise I get error: not being able to implicitly convert the return from IFantasyPremierLeagueClient. Should I either cast the result like that (PlayersData<T>)(object)await _leagueClient.LoadBootstrapStaticPlayersDataTeamsAsync(); or add a generic client class that from which to access the api's endpoint.

2021-08-30 09:38 UTC, it-kyrylo commented on ProjectA/ProjectA/Clients/IFantasyPremierLeagueClient.cs
> +        Task<string> LoadBootstrapStaticPlayersDataTeamsAsync();
Oh... now I see.

So in general, here my thoughts on this:
I do not see the critical reason to use inheritance for `PerformancePlayerData` and `StatisticsPlayerData` since even each `element`  from `api/bootstrap-static/` contains all data in a single element. So my recommendation is to use `Player` with all the fields which you need. This approach will give you a couple of benefits:

- All serialization stuff will be handled by refit 
- Your repository will no longer need to be a generic
- Less complicated and easy to understand code

Let me know what do you think!

2021-08-30 11:54 UTC, it-kyrylo approved these changes

2021-08-30 11:57 UTC, merged